version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://devopsuser:<password>@cluster0.mongodb.net/devops_login_db?retryWrites=true&w=majority
      - JWT_SECRET=supersecretdevopskey
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://localhost:5000
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always